services:
  postgres:
    image: postgres:17-alpine
    restart: always
    container_name: postgres-dev
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pokemon-manager-server-dev
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
    networks:
      - pokemon-manager-dev
    ports:
      - "5432:5432"

volumes:
  pgdata-dev:
networks:
  pokemon-manager-dev:
