import type { ReactNode } from 'react';

import { Geist, Geist_Mono } from 'next/font/google';

import { UserProvider } from '@/client/features/auth/providers/UserProvider';

import type { Metadata } from 'next';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// I assume that is not a bug as it is from official Next.js docs, thats way eslint is disabled
// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <UserProvider>
          <main className="flex flex-col">{children}</main>
        </UserProvider>
      </body>
    </html>
  );
}
